---
kind: pipeline
name: default

steps:
  - name: build & test
    image: golang:1.13
    environment:
      GO_ENV: test
      AUTHORIZE_RSA:
        from_secret: AUTHORIZE_RSA
      GOOGLE_OAUTH_REDIRECT_URL:
        from_secret: GOOGLE_OAUTH_REDIRECT_URL
      GOOGLE_OAUTH_CLIENT_ID:
        from_secret: GOOGLE_OAUTH_CLIENT_ID
      GOOGLE_OAUTH_CLIENT_SECRET:
        from_secret: GOOGLE_OAUTH_CLIENT_SECRET

    commands:
      - make build
      - make test

    when:
      event:
        - push
        - pull_request
        - tag

  - name: publish
    image: plugins/docker:18
    settings:
      dockerfile: ./Dockerfile
      repo: taniwhy/mochi-match-rest
      tags: latest
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        - push

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - cd /var/www/mochi-match
        - sh deploy.sh
    when:
      event:
        - push

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOCK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOCK_TOKEN
      message: >
        {{#success build.status}}
          ✅  Build #{{build.number}} `{{repo.name}}/{{commit.branch}}` Success
          ``` {{commit.message}} ```
          duration: {{duration build.started build.finished}}
        {{else}}
          ❌  Build #{{build.number}} `{{repo.name}}/{{commit.branch}}` Failed
          ``` {{commit.message}} ```
          duration: {{duration build.started build.finished}}
        {{/success}}
    when:
      status: [success, failure]
      event:
        - push
        - pull_request
        - tag

services:
  - name: db
    image: postgres:10.5
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mochi_match
  - name: redis
    image: redis:4.0.6
    ports:
      - 6379
