settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: mochi-match-rest
    path: .
    commands:
      install:
        status: true
        method: go build -o main ./main.go
      run:
        status: true
        method: ./main
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
