// Code generated by MockGen. DO NOT EDIT.
// Source: entry_histroy_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIEntryHistoryService is a mock of IEntryHistoryService interface
type MockIEntryHistoryService struct {
	ctrl     *gomock.Controller
	recorder *MockIEntryHistoryServiceMockRecorder
}

// MockIEntryHistoryServiceMockRecorder is the mock recorder for MockIEntryHistoryService
type MockIEntryHistoryServiceMockRecorder struct {
	mock *MockIEntryHistoryService
}

// NewMockIEntryHistoryService creates a new mock instance
func NewMockIEntryHistoryService(ctrl *gomock.Controller) *MockIEntryHistoryService {
	mock := &MockIEntryHistoryService{ctrl: ctrl}
	mock.recorder = &MockIEntryHistoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIEntryHistoryService) EXPECT() *MockIEntryHistoryServiceMockRecorder {
	return m.recorder
}

// CanJoin mocks base method
func (m *MockIEntryHistoryService) CanJoin(userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanJoin", userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanJoin indicates an expected call of CanJoin
func (mr *MockIEntryHistoryServiceMockRecorder) CanJoin(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanJoin", reflect.TypeOf((*MockIEntryHistoryService)(nil).CanJoin), userID)
}

// CheckJoin mocks base method
func (m *MockIEntryHistoryService) CheckJoin(userID, roomID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckJoin", userID, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckJoin indicates an expected call of CheckJoin
func (mr *MockIEntryHistoryServiceMockRecorder) CheckJoin(userID, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckJoin", reflect.TypeOf((*MockIEntryHistoryService)(nil).CheckJoin), userID, roomID)
}
