// Code generated by MockGen. DO NOT EDIT.
// Source: game_list_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	reflect "reflect"
)

// MockGameListRepository is a mock of GameListRepository interface
type MockGameListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameListRepositoryMockRecorder
}

// MockGameListRepositoryMockRecorder is the mock recorder for MockGameListRepository
type MockGameListRepositoryMockRecorder struct {
	mock *MockGameListRepository
}

// NewMockGameListRepository creates a new mock instance
func NewMockGameListRepository(ctrl *gomock.Controller) *MockGameListRepository {
	mock := &MockGameListRepository{ctrl: ctrl}
	mock.recorder = &MockGameListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGameListRepository) EXPECT() *MockGameListRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method
func (m *MockGameListRepository) FindAll() ([]*models.GameList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*models.GameList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockGameListRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGameListRepository)(nil).FindAll))
}

// Insert mocks base method
func (m *MockGameListRepository) Insert(arg0 *models.GameList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *MockGameListRepositoryMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockGameListRepository)(nil).Insert), arg0)
}

// Update mocks base method
func (m *MockGameListRepository) Update(arg0 *models.GameList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockGameListRepositoryMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameListRepository)(nil).Update), arg0)
}

// Delete mocks base method
func (m *MockGameListRepository) Delete(arg0 *models.GameList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockGameListRepositoryMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameListRepository)(nil).Delete), arg0)
}
