// Code generated by MockGen. DO NOT EDIT.
// Source: user_detail_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	reflect "reflect"
)

// MockIUserDetailRepository is a mock of IUserDetailRepository interface
type MockIUserDetailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserDetailRepositoryMockRecorder
}

// MockIUserDetailRepositoryMockRecorder is the mock recorder for MockIUserDetailRepository
type MockIUserDetailRepositoryMockRecorder struct {
	mock *MockIUserDetailRepository
}

// NewMockIUserDetailRepository creates a new mock instance
func NewMockIUserDetailRepository(ctrl *gomock.Controller) *MockIUserDetailRepository {
	mock := &MockIUserDetailRepository{ctrl: ctrl}
	mock.recorder = &MockIUserDetailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIUserDetailRepository) EXPECT() *MockIUserDetailRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method
func (m *MockIUserDetailRepository) FindByID(id string) (*models.UserDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.UserDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockIUserDetailRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIUserDetailRepository)(nil).FindByID), id)
}

// Insert mocks base method
func (m *MockIUserDetailRepository) Insert(userDetail *models.UserDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", userDetail)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *MockIUserDetailRepositoryMockRecorder) Insert(userDetail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIUserDetailRepository)(nil).Insert), userDetail)
}

// Update mocks base method
func (m *MockIUserDetailRepository) Update(id, name, icon string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, name, icon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockIUserDetailRepositoryMockRecorder) Update(id, name, icon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUserDetailRepository)(nil).Update), id, name, icon)
}

// Delete mocks base method
func (m *MockIUserDetailRepository) Delete(userDetail *models.UserDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userDetail)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockIUserDetailRepositoryMockRecorder) Delete(userDetail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUserDetailRepository)(nil).Delete), userDetail)
}
