// Code generated by MockGen. DO NOT EDIT.
// Source: favorate_game_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	reflect "reflect"
)

// MockFavoriteGameRepository is a mock of FavoriteGameRepository interface
type MockFavoriteGameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteGameRepositoryMockRecorder
}

// MockFavoriteGameRepositoryMockRecorder is the mock recorder for MockFavoriteGameRepository
type MockFavoriteGameRepositoryMockRecorder struct {
	mock *MockFavoriteGameRepository
}

// NewMockFavoriteGameRepository creates a new mock instance
func NewMockFavoriteGameRepository(ctrl *gomock.Controller) *MockFavoriteGameRepository {
	mock := &MockFavoriteGameRepository{ctrl: ctrl}
	mock.recorder = &MockFavoriteGameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFavoriteGameRepository) EXPECT() *MockFavoriteGameRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method
func (m *MockFavoriteGameRepository) FindByID(id string) ([]*models.FavoriteGame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].([]*models.FavoriteGame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockFavoriteGameRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFavoriteGameRepository)(nil).FindByID), id)
}

// Insert mocks base method
func (m *MockFavoriteGameRepository) Insert(room *models.FavoriteGame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *MockFavoriteGameRepositoryMockRecorder) Insert(room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockFavoriteGameRepository)(nil).Insert), room)
}

// Delete mocks base method
func (m *MockFavoriteGameRepository) Delete(uID, fID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", uID, fID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockFavoriteGameRepositoryMockRecorder) Delete(uID, fID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFavoriteGameRepository)(nil).Delete), uID, fID)
}
