// Code generated by MockGen. DO NOT EDIT.
// Source: game_list_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	output "github.com/taniwhy/mochi-match-rest/domain/models/output"
	reflect "reflect"
)

// MockIGameListRepository is a mock of IGameListRepository interface
type MockIGameListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIGameListRepositoryMockRecorder
}

// MockIGameListRepositoryMockRecorder is the mock recorder for MockIGameListRepository
type MockIGameListRepositoryMockRecorder struct {
	mock *MockIGameListRepository
}

// NewMockIGameListRepository creates a new mock instance
func NewMockIGameListRepository(ctrl *gomock.Controller) *MockIGameListRepository {
	mock := &MockIGameListRepository{ctrl: ctrl}
	mock.recorder = &MockIGameListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIGameListRepository) EXPECT() *MockIGameListRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method
func (m *MockIGameListRepository) FindAll() ([]*models.GameList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*models.GameList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockIGameListRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIGameListRepository)(nil).FindAll))
}

// FindHot mocks base method
func (m *MockIGameListRepository) FindHot() ([]*output.HotGameRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHot")
	ret0, _ := ret[0].([]*output.HotGameRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindHot indicates an expected call of FindHot
func (mr *MockIGameListRepositoryMockRecorder) FindHot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHot", reflect.TypeOf((*MockIGameListRepository)(nil).FindHot))
}

// Insert mocks base method
func (m *MockIGameListRepository) Insert(arg0 *models.GameList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *MockIGameListRepositoryMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIGameListRepository)(nil).Insert), arg0)
}

// Update mocks base method
func (m *MockIGameListRepository) Update(arg0 *models.GameList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockIGameListRepositoryMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIGameListRepository)(nil).Update), arg0)
}

// Delete mocks base method
func (m *MockIGameListRepository) Delete(arg0 *models.GameList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockIGameListRepositoryMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIGameListRepository)(nil).Delete), arg0)
}
