// Code generated by MockGen. DO NOT EDIT.
// Source: game_hard_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	reflect "reflect"
)

// MockGameHardRepository is a mock of GameHardRepository interface
type MockGameHardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameHardRepositoryMockRecorder
}

// MockGameHardRepositoryMockRecorder is the mock recorder for MockGameHardRepository
type MockGameHardRepositoryMockRecorder struct {
	mock *MockGameHardRepository
}

// NewMockGameHardRepository creates a new mock instance
func NewMockGameHardRepository(ctrl *gomock.Controller) *MockGameHardRepository {
	mock := &MockGameHardRepository{ctrl: ctrl}
	mock.recorder = &MockGameHardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGameHardRepository) EXPECT() *MockGameHardRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method
func (m *MockGameHardRepository) FindAll() ([]*models.GameHard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*models.GameHard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockGameHardRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGameHardRepository)(nil).FindAll))
}

// Insert mocks base method
func (m *MockGameHardRepository) Insert(arg0 *models.GameHard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *MockGameHardRepositoryMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockGameHardRepository)(nil).Insert), arg0)
}

// Update mocks base method
func (m *MockGameHardRepository) Update(arg0 *models.GameHard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockGameHardRepositoryMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameHardRepository)(nil).Update), arg0)
}

// Delete mocks base method
func (m *MockGameHardRepository) Delete(arg0 *models.GameHard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockGameHardRepositoryMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameHardRepository)(nil).Delete), arg0)
}
