// Code generated by MockGen. DO NOT EDIT.
// Source: report_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	reflect "reflect"
)

// MockReportRepository is a mock of ReportRepository interface
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// FindAllReport mocks base method
func (m *MockReportRepository) FindAllReport() ([]*models.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllReport")
	ret0, _ := ret[0].([]*models.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllReport indicates an expected call of FindAllReport
func (mr *MockReportRepositoryMockRecorder) FindAllReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllReport", reflect.TypeOf((*MockReportRepository)(nil).FindAllReport))
}

// InsertReport mocks base method
func (m *MockReportRepository) InsertReport(report *models.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReport", report)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertReport indicates an expected call of InsertReport
func (mr *MockReportRepositoryMockRecorder) InsertReport(report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReport", reflect.TypeOf((*MockReportRepository)(nil).InsertReport), report)
}

// DeleteReport mocks base method
func (m *MockReportRepository) DeleteReport(report *models.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReport", report)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReport indicates an expected call of DeleteReport
func (mr *MockReportRepositoryMockRecorder) DeleteReport(report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReport", reflect.TypeOf((*MockReportRepository)(nil).DeleteReport), report)
}
