// Code generated by MockGen. DO NOT EDIT.
// Source: chat_post_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	output "github.com/taniwhy/mochi-match-rest/domain/models/output"
	reflect "reflect"
)

// MockIChatPostRepository is a mock of IChatPostRepository interface
type MockIChatPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIChatPostRepositoryMockRecorder
}

// MockIChatPostRepositoryMockRecorder is the mock recorder for MockIChatPostRepository
type MockIChatPostRepositoryMockRecorder struct {
	mock *MockIChatPostRepository
}

// NewMockIChatPostRepository creates a new mock instance
func NewMockIChatPostRepository(ctrl *gomock.Controller) *MockIChatPostRepository {
	mock := &MockIChatPostRepository{ctrl: ctrl}
	mock.recorder = &MockIChatPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIChatPostRepository) EXPECT() *MockIChatPostRepositoryMockRecorder {
	return m.recorder
}

// FindByRoomID mocks base method
func (m *MockIChatPostRepository) FindByRoomID(id string) ([]*output.ChatPostResBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoomID", id)
	ret0, _ := ret[0].([]*output.ChatPostResBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoomID indicates an expected call of FindByRoomID
func (mr *MockIChatPostRepositoryMockRecorder) FindByRoomID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoomID", reflect.TypeOf((*MockIChatPostRepository)(nil).FindByRoomID), id)
}

// FindByRoomIDAndLimit mocks base method
func (m *MockIChatPostRepository) FindByRoomIDAndLimit(id string, limit int) ([]*output.ChatPostResBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoomIDAndLimit", id, limit)
	ret0, _ := ret[0].([]*output.ChatPostResBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoomIDAndLimit indicates an expected call of FindByRoomIDAndLimit
func (mr *MockIChatPostRepositoryMockRecorder) FindByRoomIDAndLimit(id, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoomIDAndLimit", reflect.TypeOf((*MockIChatPostRepository)(nil).FindByRoomIDAndLimit), id, limit)
}

// FindByRoomIDAndOffset mocks base method
func (m *MockIChatPostRepository) FindByRoomIDAndOffset(id, offset string) ([]*output.ChatPostResBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoomIDAndOffset", id, offset)
	ret0, _ := ret[0].([]*output.ChatPostResBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoomIDAndOffset indicates an expected call of FindByRoomIDAndOffset
func (mr *MockIChatPostRepositoryMockRecorder) FindByRoomIDAndOffset(id, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoomIDAndOffset", reflect.TypeOf((*MockIChatPostRepository)(nil).FindByRoomIDAndOffset), id, offset)
}

// FindByRoomIDAndLimitAndOffset mocks base method
func (m *MockIChatPostRepository) FindByRoomIDAndLimitAndOffset(id, offset string, limit int) ([]*output.ChatPostResBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoomIDAndLimitAndOffset", id, offset, limit)
	ret0, _ := ret[0].([]*output.ChatPostResBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoomIDAndLimitAndOffset indicates an expected call of FindByRoomIDAndLimitAndOffset
func (mr *MockIChatPostRepositoryMockRecorder) FindByRoomIDAndLimitAndOffset(id, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoomIDAndLimitAndOffset", reflect.TypeOf((*MockIChatPostRepository)(nil).FindByRoomIDAndLimitAndOffset), id, offset, limit)
}

// Insert mocks base method
func (m *MockIChatPostRepository) Insert(room *models.ChatPost) (*output.ChatPostResBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", room)
	ret0, _ := ret[0].(*output.ChatPostResBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockIChatPostRepositoryMockRecorder) Insert(room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIChatPostRepository)(nil).Insert), room)
}

// Delete mocks base method
func (m *MockIChatPostRepository) Delete(room *models.ChatPost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockIChatPostRepositoryMockRecorder) Delete(room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIChatPostRepository)(nil).Delete), room)
}
