// Code generated by MockGen. DO NOT EDIT.
// Source: report_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	reflect "reflect"
)

// MockIReportRepository is a mock of IReportRepository interface
type MockIReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIReportRepositoryMockRecorder
}

// MockIReportRepositoryMockRecorder is the mock recorder for MockIReportRepository
type MockIReportRepositoryMockRecorder struct {
	mock *MockIReportRepository
}

// NewMockIReportRepository creates a new mock instance
func NewMockIReportRepository(ctrl *gomock.Controller) *MockIReportRepository {
	mock := &MockIReportRepository{ctrl: ctrl}
	mock.recorder = &MockIReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIReportRepository) EXPECT() *MockIReportRepositoryMockRecorder {
	return m.recorder
}

// FindAllReport mocks base method
func (m *MockIReportRepository) FindAllReport() ([]*models.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllReport")
	ret0, _ := ret[0].([]*models.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllReport indicates an expected call of FindAllReport
func (mr *MockIReportRepositoryMockRecorder) FindAllReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllReport", reflect.TypeOf((*MockIReportRepository)(nil).FindAllReport))
}

// InsertReport mocks base method
func (m *MockIReportRepository) InsertReport(report *models.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReport", report)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertReport indicates an expected call of InsertReport
func (mr *MockIReportRepositoryMockRecorder) InsertReport(report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReport", reflect.TypeOf((*MockIReportRepository)(nil).InsertReport), report)
}

// DeleteReport mocks base method
func (m *MockIReportRepository) DeleteReport(report *models.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReport", report)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReport indicates an expected call of DeleteReport
func (mr *MockIReportRepositoryMockRecorder) DeleteReport(report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReport", reflect.TypeOf((*MockIReportRepository)(nil).DeleteReport), report)
}
