@startuml
title ユースケース図
skinparam packageStyle rectangle

actor :管理人: as admin

rectangle ユーザー設定 {
  (OAuthで\nサインアップできる)
  (OAuthで\nログインできる)
  (ログアウトできる)
  (ユーザー名を編集できる)
  (ユーザー画像を変更できる)
  (お気に入りゲームを編集できる)
  (管理人は全てのユーザー情報を\n閲覧,編集できる)
}

rectangle 他人ユーザー操作 {
  (他人ユーザー違反報告ができる)
  (他人ユーザーブロックができる)
  (他人ユーザーブロック解除ができる)
}

rectangle 検索 {
  (ルーム検索できる)
  (検索の絞り込みができる)
}

rectangle ルーム {
  (ルームを作成できる)
  (ルームを削除できる)
  (ルームに参加できる)
  (ルームを退出できる)
  (ルーム違反報告ができる)
  (メンバーを追い出せる)
}

rectangle チャット {
  (チャットができる)
}


admin -- (管理人は全てのユーザー情報を\n閲覧,編集できる)

@enduml