@startuml
title 状態遷移図
hide empty description
left to right direction

[*] --> 未ログイン状態
state ログイン状態 {
    [*] --> 未申請
    未申請 --> 申請中 : 申請を送る
    未申請 --> 被申請 : 申請が送られる
    申請中 -left-> 未申請 : 拒否される
    被申請 -left-> 未申請 : 拒否する
    申請中 --> マッチング : 承認される
    被申請 --> マッチング : 承認する
}
未ログイン状態 --> ログイン状態 : ログインする
state 未ログイン状態 {
    ブロック --> 相互ブロック : ブロックされる
    被ブロック --> 相互ブロック : ブロックする
    相互ブロック -left-> ブロック : 解除される
    相互ブロック -left-> 被ブロック : 解除する
    ブロック -up-> 未申請 : [ブロック解除する]
    被ブロック -up-> 未申請 : [ブロック解除される]
} 

@enduml