// Code generated by MockGen. DO NOT EDIT.
// Source: chat_post_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	models "github.com/taniwhy/mochi-match-rest/domain/models"
	reflect "reflect"
)

// MockIChatPostUseCase is a mock of IChatPostUseCase interface
type MockIChatPostUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIChatPostUseCaseMockRecorder
}

// MockIChatPostUseCaseMockRecorder is the mock recorder for MockIChatPostUseCase
type MockIChatPostUseCaseMockRecorder struct {
	mock *MockIChatPostUseCase
}

// NewMockIChatPostUseCase creates a new mock instance
func NewMockIChatPostUseCase(ctrl *gomock.Controller) *MockIChatPostUseCase {
	mock := &MockIChatPostUseCase{ctrl: ctrl}
	mock.recorder = &MockIChatPostUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIChatPostUseCase) EXPECT() *MockIChatPostUseCaseMockRecorder {
	return m.recorder
}

// FindByRoomID mocks base method
func (m *MockIChatPostUseCase) FindByRoomID(id string) ([]*models.ChatPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoomID", id)
	ret0, _ := ret[0].([]*models.ChatPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoomID indicates an expected call of FindByRoomID
func (mr *MockIChatPostUseCaseMockRecorder) FindByRoomID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoomID", reflect.TypeOf((*MockIChatPostUseCase)(nil).FindByRoomID), id)
}

// FindByRoomIDAndLimit mocks base method
func (m *MockIChatPostUseCase) FindByRoomIDAndLimit(id, limit string) ([]*models.ChatPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoomIDAndLimit", id, limit)
	ret0, _ := ret[0].([]*models.ChatPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoomIDAndLimit indicates an expected call of FindByRoomIDAndLimit
func (mr *MockIChatPostUseCaseMockRecorder) FindByRoomIDAndLimit(id, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoomIDAndLimit", reflect.TypeOf((*MockIChatPostUseCase)(nil).FindByRoomIDAndLimit), id, limit)
}

// FindByRoomIDAndOffset mocks base method
func (m *MockIChatPostUseCase) FindByRoomIDAndOffset(id, offset string) ([]*models.ChatPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoomIDAndOffset", id, offset)
	ret0, _ := ret[0].([]*models.ChatPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoomIDAndOffset indicates an expected call of FindByRoomIDAndOffset
func (mr *MockIChatPostUseCaseMockRecorder) FindByRoomIDAndOffset(id, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoomIDAndOffset", reflect.TypeOf((*MockIChatPostUseCase)(nil).FindByRoomIDAndOffset), id, offset)
}

// FindByRoomIDAndLimitAndOffset mocks base method
func (m *MockIChatPostUseCase) FindByRoomIDAndLimitAndOffset(id, offset, limit string) ([]*models.ChatPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoomIDAndLimitAndOffset", id, offset, limit)
	ret0, _ := ret[0].([]*models.ChatPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoomIDAndLimitAndOffset indicates an expected call of FindByRoomIDAndLimitAndOffset
func (mr *MockIChatPostUseCaseMockRecorder) FindByRoomIDAndLimitAndOffset(id, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoomIDAndLimitAndOffset", reflect.TypeOf((*MockIChatPostUseCase)(nil).FindByRoomIDAndLimitAndOffset), id, offset, limit)
}

// Insert mocks base method
func (m *MockIChatPostUseCase) Insert(arg0 *gin.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *MockIChatPostUseCaseMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIChatPostUseCase)(nil).Insert), arg0)
}
