@startuml

actor ユーザー

participant ReactApp
participant WebsocketServer
participant RestAPIServer

ユーザー -> ReactApp : ログイン状態でサイトにアクセス
ReactApp -> RestAPIServer : ルーム作成APIを叩く
RestAPIServer --> ReactApp : レスポンス
ReactApp -> RestAPIServer : ルーム参加APIを叩く
RestAPIServer --> ReactApp : レスポンス
ReactApp -> WebsocketServer : ルームにJOIN

@enduml
