@startuml

actor ユーザー

participant ReactApp
participant WebsocketServer
participant RestAPIServer

ユーザー -> ReactApp : ログイン状態でサイトにアクセス
ReactApp -> RestAPIServer : ルーム一覧APIを叩く
RestAPIServer --> ReactApp : レスポンス
ReactApp -> RestAPIServer : ルーム参加APIを叩く
RestAPIServer --> ReactApp : レスポンス
ReactApp -> WebsocketServer : ルームにJOIN
WebsocketServer -> ReactApp : ルーム参加者に通知


@enduml
